workflow:
  rules:
    - if: "$CI_COMMIT_BRANCH"

stages:
  - test
  - build

test:
  stage: test
  tags: [docker]
  image: python:3.8-slim
  variables:
    POETRY_HOME: /opt/poetry
  script:
    - apt update && apt install -y curl
    - curl -sSL https://install.python-poetry.org | python -
    - $POETRY_HOME/bin/poetry config virtualenvs.in-project true
    - $POETRY_HOME/bin/poetry install
    - $POETRY_HOME/bin/poetry run yapf -- --recursive --parallel --diff .
    - $POETRY_HOME/bin/poetry run pytest -- --cov=./ --cov-config=.coveragerc --junitxml=pytest-report.xml
  artifacts:
    when: always
    reports:
      junit: pytest-report.xml
  cache:
    key:
      files:
        - poetry.lock
    paths:
      - .venv

# See more: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
build:
  stage: build
  tags: [docker]
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --target production
      --destination $IMAGE_TAG
      --skip-unused-stages
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
